### ISSUE TITLE
"user" is a restricted keyword in postgres

### ISSUE THREAD

**Issue by Danielss89** [ZF-Commons/ZfcUserDoctrineORM#77]
As headline says, "user" is a restricted keyword in postgres, and that's what we are using for table name.
If we add backticks it works on web, but in CLI, when running `./vendor/bin/doctrine-module orm:validate-schema` it says 

```
[Mapping]  OK - The mapping files are correct.
[Database] FAIL - The database schema is not in sync with the current mapping file
```

Changing the table name to `users` fixes everything, but that would be a major BC break.

**Comment by tdutrion** [comment]
I'd like to reopen the issue...

With doctrine dbal up to date:
```
"name": "doctrine/dbal",
"version": "v2.5.1",
```

PostgreSQL is running in a docker container on the default postgres image from docker hub (no impact here): PostgreSQL 9.4.1 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit

-----------
**Doctrine\DBAL\Exception\InvalidFieldNameException**

File:
```
/code/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php:72
```

Message:
```
An exception occurred while executing 'SELECT t0.username AS username_1, t0.email AS email_2, t0.display_name AS display_name_3, t0.password AS password_4, t0.state AS state_5, t0.user_id AS user_id_6 FROM user t0 WHERE t0.email = ? LIMIT 1' with params ["test@email.com"]:

SQLSTATE[42703]: Undefined column: 7 ERROR:  column t0.username does not exist
LINE 1: SELECT t0.username AS username_1, t0.email AS email_2, t0.di...
               ^
``` 

-----------

Running the sql query with double quotes surrounding the table name solve the problem (directly in PgAdmin for test purpose).
