### ISSUE TITLE
fatal error getEnableDefaultEntities

### ISSUE THREAD

**Issue by stijnhau** [ZF-Commons/ZfcUserDoctrineORM#87]
Fatal error: Call to undefined method ZfcUser\Options\ModuleOptions::getEnableDefaultEntities() in D:\Dropbox (Persoonlijk)\Workspace\True-Life\vendor\zf-commons\zfc-user-doctrine-orm\Module.php on line 16

The latest version of this module isn't working anymore with zfcUser

**Comment by Danielss89** [comment]
This is when you use ZfcUser 2.x, please only use 1.x
