### ISSUE TITLE
Requires *.0

### ISSUE THREAD

**Issue by jarrettj** [ZF-Commons/ZfcUserDoctrineORM#90]
It longer works with doctrine/doctrine-orm-module: master? It worked before. This started happening this week. 

I now get:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zf-commons/zfc-user-doctrine-orm 1.0.0 requires doctrine/doctrine-orm-module 0.* -> no matching package found.
    - zf-commons/zfc-user-doctrine-orm 1.0.0 requires doctrine/doctrine-orm-module 0.* -> no matching package found.
    - Installation request for zf-commons/zfc-user-doctrine-orm 1.* -> satisfiable by zf-commons/zfc-user-doctrine-orm[1.0.0].
```
When trying to update composer packages.

This has not happened before, and I need to use doctrine/doctrine-orm-module: master.

Any help much appreciated. Thanks.

Cheers.

**Comment by VadimIzmalkov** [comment]
Have the same problem

**Comment by VadimIzmalkov** [comment]
My problem resolved by using last stable versions:
```
"zf-commons/zfc-base": ">=0.1.2",
"zf-commons/zfc-user": ">=1.2.2",

**Comment by Danielss89** [comment]
yeah, you should not use master branch(2.x). Only the releases in the releases tab.
