### ISSUE TITLE
Doctrine\ORM\EntityManager is Deprecated

### ISSUE THREAD

**Issue by claytondaley** [ZF-Commons/ZfcUserDoctrineORM#91]
Per [DoctrineORMModule](https://github.com/doctrine/DoctrineORMModule/blob/master/UPGRADE.md#040) "An alias has been set to reference Doctrine\ORM\EntityManager to help with BC but it is deprecated and will be removed in the future. The new service name is doctrine.entitymanager.orm_default."

This project currently uses the old reference.

**Comment by Danielss89** [comment]
Thx, fixed in #92
