### ISSUE TITLE
Package has a 0.* constraint on DoctrineORMModule, while version 1.0 has been released

### ISSUE THREAD

**Issue by DannyvdSluijs** [ZF-Commons/ZfcUserDoctrineORM#97]
In the composer.json on line 25 [https://github.com/ZF-Commons/ZfcUserDoctrineORM/blob/master/composer.json#L25]
 you can see the doctrine-orm-module constraint is set to 0.\* whilst version 1.0.0 is available.

**Comment by angurova** [comment]
I have the same problem

**Comment by Kwido** [comment]
Had the same issue. Forked it  (https://github.com/Kwido/ZfcUserDoctrineORM) , fixed it and made a PR: #98. Feel free to use my fork untill it's fixed or create your own fork and fix it for the time being.

Haven't found any problems on upgrading the version of docrine-orm-module. Works like a charm!

**Comment by pensiero** [comment]
+1

**Comment by pensiero** [comment]
@Kwido the PR #98 is closed, why?

**Comment by Kwido** [comment]
@pensiero as a [commit](https://github.com/ZF-Commons/ZfcUserDoctrineORM/commit/c59d46b7bc73f2b753b855757339783e4da696b0) is already on the master branch setting the doctrine-orm-module version to 1.0+

**Comment by pensiero** [comment]
@Kwido however the [v1.0.1](https://github.com/ZF-Commons/ZfcUserDoctrineORM/releases/tag/1.0.1) is 2 commit behind master, and it doesn't include the requirement of `doctrine/doctrine-orm-module ~1.0`

@Danielss89 can you release a v1.0.2 that contains those commit?

Thanks

**Comment by pensiero** [comment]
@Danielss89 or anyone have permission: any news about the creation of the new release?
Actually I have `dev-master` on my composer, that it's not really nice for a production environment.

Thanks

**Comment by pensiero** [comment]
Anybody?

**Comment by andrewdisney** [comment]
+1

**Comment by Danielss89** [comment]
Tagged 1.0.2

**Comment by pensiero** [comment]
@Danielss89, the `v1.0.2` needs a [commit](https://github.com/ZF-Commons/ZfcUser/commit/27e859807dc945557194510f04def07536ed8f82) on `ZfcUser` released on the master branch but not tagged: https://github.com/ZF-Commons/ZfcUser/compare/1.4.4...1.x

Can you tag a new release also in `ZfcUser`? Thanks a lot

**Comment by pensiero** [comment]
Anybody?

**Comment by Danielss89** [comment]
I will take a look tonight and tag ZfcUser

**Comment by pensiero** [comment]
Thanks @Danielss89

**Comment by pensiero** [comment]
I took a look better, maybe that's not the problem.
If I specify: 
```
    "zf-commons/zfc-user-doctrine-orm": "1.0.*",
```
it says:
```
( ! ) Fatal error: Uncaught Error: Call to undefined method ZfcUser\Options\ModuleOptions::getEnableDefaultEntities() in /var/www/vendor/zf-commons/zfc-user-doctrine-orm/Module.php on line 16
```

I saw that there is no `getEnableDefaultEntities()` in the [ModuleOption.php](https://github.com/ZF-Commons/ZfcUser/blob/master/src/ZfcUser/Options/ModuleOptions.php) file, even in the latest version of ZfcUser, but there is a `getEnableDefaultEntities()` method inside the [ModuleOption.php](https://github.com/ZF-Commons/ZfcUserDoctrineORM/blob/master/src/ZfcUserDoctrineORM/Options/ModuleOptions.php) of ZfcUserDoctrineORM... maybe my config is wrong somewhere?

**Comment by pensiero** [comment]
I reported the error also here some months ago: https://github.com/Kwido/ZfcUserDoctrineORM/compare/master...ZF-Commons:master

**Comment by pensiero** [comment]
Temporary I solved this way:
```
    "zf-commons/zfc-user": "1.*",
    "zf-commons/zfc-user-doctrine-orm": "1.0.*",
```
But as @Kwido said [here](https://github.com/Kwido/ZfcUserDoctrineORM/compare/master...ZF-Commons:master#commitcomment-18468374) I think that probably is better to specify that constraint inside the composer of this project.

PS: it's not necessary to tag `ZfcUser` now
